global:
  scrape_interval: 15s

scrape_configs:
  # NOTE: dockerで使う場合必要 /var/run/docker.sock:/var/run/docker.sock
  # - job_name: dynamic-container-target
  #   docker_sd_configs:
  #     - host: unix:///var/run/docker.sock
  #       refresh_interval: 30s
  #   relabel_configs:
  #     - source_labels: [ __meta_docker_container_label_prometheus_target ]
  #       action: keep
  #       regex: .+
  #     - source_labels: [ __meta_docker_container_label_prometheus_target ]
  #       action: replace
  #       target_label: job
  #     - source_labels: [ __address__ ]
  #       action: replace
  #       target_label: __address__
  #       regex: '(.*):\d+'
  #       replacement: '${1}:9464'
  - job_name: otel-collector
    scrape_interval: 5s
    static_configs:
      - targets: [ otel-collector:8889 ]
