apiVersion: 1

datasources:
  # Logs
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      timeout: 60
      maxLines: 1000
  # Metrics
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
  # Traces
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
  # Example database
  - name: MySQL
    type: mysql
    url: mysql:3306
    database: laravel
    user: root
    secureJsonData:
      password: password
